services:
  db:
    image: postgres:15
    container_name: db_transparencia
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    networks:
      - api-network

  backend:
    build: .
    container_name: backend_transparencia
    ports:
      - "8080:8080"
    # Aqui o Compose joga TODO o conteúdo do .env direto pro Spring Boot
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx256m
    networks:
      - api-network

networks:
  api-network:
    name: api-network
    driver: bridge
    external: true